
services: 

    # Session storage
    redis:
        build: 
            context: .docker/redis
            dockerfile: Dockerfile
        restart: always


    app:
        build: 
            context: . 
            dockerfile: .docker/app/Dockerfile
        volumes: 
            - "./app:/var/www/html"
        env_file:
            - ".env"
        depends_on:
            - redis
            - db
        ports:
            - "${APP_EXTERNAL_PORT}:8080"


    db:
        build:
            context: .
            dockerfile: .docker/mongo/Dockerfile
            args:
                - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
                - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
                - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_HOST: db
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        volumes:
            - "./.var/db_data:/data/db"
        



