
services: 

    redis:
        build: 
            context: .docker/redis
            dockerfile: Dockerfile
        restart: always


    app:
        build: 
            context: . 
            dockerfile: .docker/app/Dockerfile
        volumes: 
            - "./app:/var/www/html"
        env_file:
            - ".env"
        depends_on:
            - redis
            - db
        ports:
            - "${APP_EXTERNAL_PORT}:8080"


    db:
        build:
            context: .
            dockerfile: .docker/mongo/Dockerfile
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
            MONGO_INITDB_HOST: ${DB_HOST}
            MONGO_INITDB_DATABASE: ${DB_NAME}
        volumes:
            - "./.var/db_data:/data/db"
        



