
services:
    # Web client to access container 'redis'
    # When in production, should be removed
    redis-ui:
        image: marian/rebrow
        ports: 
            - "${REDIS_UI_EXTERNAL_PORT}:5001"
        depends_on: 
            - redis


    # Client to access and inspect the DB
    # Should be removed when in production
    mongo-client:
        image: mongo-express:1-20-alpine3.19
        ports:
        - "${DB_UI_EXTERNAL_PORT}:8081"
        environment:
            ME_CONFIG_MONGODB_SERVER: ${DB_HOST}
            ME_CONFIG_BASICAUTH: 'false'
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
            ME_CONFIG_MONGODB_URL: ${DB_URI}
        depends_on:
            - db
        links:
          - db:db
